"""
YAMNet class names that map to our onomatopoeia sound categories.
Maps from YAMNet's 521 audio classes to our simplified sound categories.
"""

YAMNET_CLASS_MAPPINGS = {
    # Impact/Explosive - Expanded for better detection
    'Explosion': 'explosion',
    'Gunshot, gunfire': 'explosion',  # Often similar to explosions
    'Burst, pop': 'explosion',
    'Breaking': 'crash',
    'Glass': 'glass',
    'Slam': 'slam',
    'Thud': 'thud',
    'Bang': 'explosion',  # Generic bang -> explosion
    'Boom': 'explosion',  # Direct boom sound
    'Artillery fire': 'explosion',
    'Cap gun': 'explosion',
    'Gunshot': 'explosion',
    
    # Thud variants
    'Thunk': 'heavy_thud',
    'Clunk': 'heavy_thud',
    'Plop': 'soft_thud',
    'Splat': 'soft_thud',
    
    # Crunch/Break sounds
    'Crushing': 'crunch',
    'Crumpling, crinkling': 'crunch',
    'Tearing': 'break',
    'Rip': 'break',
    'Crack': 'crackle',
    
    # Combat sounds
    'Slap, smack': 'punch',
    'Whip': 'hit',
    'Whack, thwack': 'hit',
    
    # Gun/Weapon sounds
    'Mechanisms': 'gun_load',
    'Clicking': 'gun_load',
    'Sliding door': 'reload',
    'Latch': 'gun_load',
    
    # Electronic
    'Bell': 'bell',
    'Buzzer': 'buzz',
    'Beep, bleep': 'beep',
    'Click': 'click',
    'Alarm': 'alarm',
    'Ding': 'bell',
    'Telephone bell ringing': 'phone',
    'Ringtone': 'phone',
    'Computer keyboard': 'computer',
    'Typing': 'computer',
    'Printer': 'printer',
    
    # Movement/Air
    'Whoosh, swoosh, swish': 'whoosh',
    'Pop': 'pop',
    'Whistle': 'whistle',
    'Siren': 'siren',
    'Wind noise (microphone)': 'wind',
    'Whoosh': 'whoosh',
    'Swoosh': 'whoosh',
    'Wind': 'wind',
    
    # Water/Nature
    'Splash, splatter': 'splash',
    'Thunder': 'explosion',  # Thunder is like explosion
    'Thunderstorm': 'explosion',
    'Rain': 'rain',
    'Water': 'splash',
    'Drip': 'drip',
    'Pour': 'pour',
    'Gurgling': 'bubble',
    'Bubble': 'bubble',
    'Fire': 'fire',
    'Crackle': 'fire',
    
    # Animal sounds - Dogs
    'Dog': 'dog',
    'Bark': 'dog',
    'Bow-wow': 'dog',
    'Growling': 'dog',
    'Whimper': 'dog',
    
    # Animal sounds - Cats
    'Cat': 'cat',
    'Meow': 'cat',
    'Purr': 'cat',
    'Hiss': 'snake',  # Can be cat or snake
    'Yowl': 'cat',
    
    # Animal sounds - Birds
    'Bird': 'bird',
    'Chirp, tweet': 'bird',
    'Squawk': 'bird',
    'Crow': 'bird',
    'Rooster': 'bird',
    'Owl': 'bird',
    
    # Animal sounds - Farm animals
    'Cattle, bovine': 'cow',
    'Moo': 'cow',
    'Pig': 'pig',
    'Oink': 'pig',
    'Horse': 'horse',
    'Neigh, whinny': 'horse',
    'Sheep': 'sheep',
    'Bleat': 'sheep',
    
    # Animal sounds - Wild animals
    'Lion': 'lion',
    'Roar': 'lion',  # Could be lion, bear, or engine
    'Bear': 'bear',
    'Wolf': 'wolf',
    'Howl': 'wolf',
    'Snake': 'snake',
    'Rattle': 'snake',
    'Frog': 'frog',
    'Croak': 'frog',
    'Insect': 'insect',
    'Bee, wasp, etc.': 'insect',
    'Cricket': 'insect',
    'Mosquito': 'insect',
    
    # Human sounds
    'Applause': 'applause',
    'Clapping': 'applause',
    'Footsteps': 'footsteps',
    'Walk, footsteps': 'footsteps',
    'Run': 'footsteps',
    'Knock': 'knock',
    'Tap': 'knock',
    'Sneeze': 'sneeze',
    'Sneezing': 'sneeze',
    'Cough': 'cough',
    'Laughter': 'laugh',
    'Giggle': 'laugh',
    'Chuckle, chortle': 'laugh',
    'Gasp': 'gasp',
    'Sigh': 'gasp',
    'Breathing': 'gasp',
    'Whispering': 'whisper',
    
    # Vehicles
    'Car': 'car_horn',
    'Vehicle horn, car horn, honking': 'car_horn',
    'Motor vehicle (road)': 'engine',
    'Truck': 'truck',
    'Motorcycle': 'motorcycle',
    'Bus': 'engine',
    'Accelerating, revving, vroom': 'engine',
    'Tire squeal': 'brakes',
    'Skidding': 'brakes',
    'Brake': 'brakes',
    
    # Food/Eating
    'Chewing, mastication': 'chew',
    'Biting': 'bite',
    'Crunch': 'crunch',
    'Munching': 'chew',
    'Slurp': 'slurp',
    'Sizzle': 'sizzle',
    'Frying (food)': 'sizzle',
    'Boiling': 'boil',
    
    # Technology
    'Camera': 'camera',
    'Phone': 'phone',
    'Smartphone': 'phone',
    
    # Miscellaneous
    'Zipper (clothing)': 'zipper',
    'Rustle': 'paper',
    'Crumpling, crinkling': 'paper',
    'Squeak': 'rubber',
    'Bounce': 'spring',
    'Boing': 'spring',
    'Door': 'door',
    'Creak': 'door',
    'Wood': 'thud',
    'Metal': 'crash',
    'Scissors': 'click',
    'Scrape': 'scratch',
    
    # Musical Instruments - Strings
    'Guitar': 'guitar',
    'Acoustic guitar': 'guitar',
    'Electric guitar': 'guitar',
    'Bass guitar': 'guitar',
    'Banjo': 'banjo',
    'Harp': 'harp',
    'Violin, fiddle': 'violin',
    'Viola': 'violin',
    'Cello': 'violin',
    'Double bass': 'violin',
    'Sitar': 'guitar',
    'Mandolin': 'guitar',
    'Ukulele': 'guitar',
    
    # Musical Instruments - Piano & Keys
    'Piano': 'piano',
    'Electric piano': 'piano',
    'Organ': 'organ',
    'Hammond organ': 'organ',
    'Synthesizer': 'organ',
    'Harpsichord': 'piano',
    'Accordion': 'accordion',
    'Harmonica': 'harmonica',
    
    # Musical Instruments - Wind
    'Trumpet': 'trumpet',
    'Trombone': 'trumpet',
    'French horn': 'trumpet',
    'Tuba': 'tuba',
    'Flute': 'flute',
    'Saxophone': 'saxophone',
    'Clarinet': 'clarinet',
    'Oboe': 'flute',
    'Bagpipes': 'bagpipes',
    'Harmonica': 'harmonica',
    'Recorder': 'flute',
    
    # Musical Instruments - Percussion
    'Drum': 'drums',
    'Drum kit': 'drums',
    'Snare drum': 'drums',
    'Bass drum': 'drums',
    'Timpani': 'drums',
    'Cymbal': 'cymbals',
    'Hi-hat': 'cymbals',
    'Gong': 'cymbals',
    'Xylophone': 'xylophone',
    'Marimba': 'xylophone',
    'Vibraphone': 'xylophone',
    'Tambourine': 'tambourine',
    'Cowbell': 'bell',
    'Wood block': 'click',
    'Castanets': 'click',
    'Triangle': 'ping',
    
    # Speech & Human Sounds Extended
    'Speech': 'speech',
    'Conversation': 'speech',
    'Narration, monologue': 'speech',
    'Shouting': 'shout',
    'Yelling': 'yell',
    'Screaming': 'scream',
    'Whispering': 'whisper',
    'Singing': 'singing',
    'Humming': 'humming',
    'Whistling': 'whistle_human',
    'Burping, eructation': 'burp',
    'Hiccup': 'hiccup',
    'Yawn': 'yawn',
    'Snoring': 'snoring',
    'Breathing': 'gasp',
    'Sigh': 'sigh',
    'Groan': 'groan',
    'Sob': 'sob',
    'Babbling': 'chatter',
    'Cheering': 'cheer',
    'Booing': 'boo',
    'Crowd': 'crowd_cheer',
    
    # Vehicles Extended
    'Aircraft': 'airplane',
    'Helicopter': 'helicopter',
    'Fixed-wing aircraft, airplane': 'airplane',
    'Jet engine': 'airplane',
    'Propeller, airscrew': 'airplane',
    'Train': 'train',
    'Rail transport': 'train',
    'Train whistle': 'train',
    'Steam locomotive': 'train',
    'Subway, metro, underground': 'subway',
    'Ship': 'ship',
    'Sailboat, sailing ship': 'ship',
    'Motorboat, speedboat': 'boat',
    'Boat, Water vehicle': 'boat',
    'Bicycle': 'bicycle',
    'Skateboard': 'skateboard',
    'Emergency vehicle': 'emergency_siren',
    'Police car (siren)': 'police_siren',
    'Ambulance (siren)': 'ambulance',
    'Fire engine, fire truck (siren)': 'fire_truck',
    'Bus': 'bus',
    
    # Tools & Machinery
    'Power tool': 'drill',
    'Drill': 'drill',
    'Hammer': 'hammer',
    'Jackhammer': 'jackhammer',
    'Chainsaw': 'chainsaw',
    'Sawing': 'saw',
    'Filing (rasp)': 'filing',
    'Sanding': 'sandpaper',
    'Vacuum cleaner': 'vacuum',
    'Sewing machine': 'sewing_machine',
    'Lawn mower': 'lawnmower',
    'Leaf blower': 'wind',
    'Chainsaw': 'chainsaw',
    
    # Kitchen & Household
    'Microwave oven': 'microwave',
    'Dishwasher': 'dishwasher',
    'Washing machine': 'washing_machine',
    'Clothes dryer, tumble dryer': 'washing_machine',
    'Blender': 'blender_kitchen',
    'Food processor': 'blender_kitchen',
    'Mixer': 'mixer',
    'Kettle whistle': 'kettle',
    'Toaster': 'toaster',
    'Timer': 'timer',
    'Doorbell': 'doorbell',
    'Door lock': 'lock',
    'Drawer open or close': 'drawer',
    'Cupboard open or close': 'cabinet',
    
    # Weather & Environment
    'Wind': 'wind',
    'Gust, wind': 'wind_strong',
    'Rain on surface': 'rain',
    'Raindrop': 'rain',
    'Thunderstorm': 'storm',
    'Hail': 'hail',
    'Earthquake': 'earthquake',
    'Volcano': 'volcano',
    'Stream': 'stream',
    'Waterfall': 'waterfall',
    'Ocean': 'ocean_waves',
    'Waves, surf': 'ocean_waves',
    'River': 'river',
    
    # More Animals Extended
    'Elephant': 'elephant',
    'Monkey': 'monkey',
    'Goat': 'goat',
    'Duck': 'duck',
    'Chicken, rooster': 'chicken',
    'Turkey': 'turkey',
    'Goose': 'goose',
    'Cricket': 'cricket',
    'Bee, wasp, etc.': 'bee',
    'Fly, housefly': 'fly',
    'Owl': 'owl',
    'Hawk': 'hawk',
    'Crow': 'crow',
    'Seagull': 'seagull',
    'Whale vocalization': 'whale',
    'Dolphin': 'dolphin',
    'Seal': 'seal',
    'Mouse': 'mouse',
    'Rat': 'rat',
    'Bat': 'bat',
    
    # Sports & Outdoor
    'Whistle': 'whistle_sport',
    'Cheering': 'crowd_cheer',
    'Booing': 'crowd_boo',
    'Bounce': 'ball_bounce',
    'Tennis': 'tennis',
    'Golf': 'golf',
    'Bowling': 'bowling',
    'Swimming pool': 'swimming',
    'Diving': 'diving',
    'Running': 'running',
    'Walk, footsteps': 'walking',
    'Marching': 'marching',
    'Skateboard': 'skateboard_trick',
    
    # Electronic Devices
    'Notification': 'notification',
    'Text message': 'text_message',
    'Email': 'email',
    'Video game': 'video_game',
    'Radio': 'radio',
    'Television': 'tv_static',
    'Static': 'radio_static',
    'Dial tone': 'dial_tone',
    'Busy signal': 'busy_signal',
    'Fax machine': 'fax',
    'Walkie-talkie': 'walkie_talkie',
    
    # Environmental Sounds
    'Fire': 'fire',
    'Fireworks': 'explosion',
    'Firecracker': 'explosion',
    'Cap gun': 'explosion',
    'Burst, pop': 'pop',
    'Finger snapping': 'snap',
    'Hands': 'clap',
    'Heart sounds, heartbeat': 'thud',
    'Heart murmur': 'whisper',
    
    # Additional Human Sounds
    'Baby cry, infant cry': 'cry',
    'Baby laughter': 'giggle',
    'Child speech, kid speaking': 'speech',
    'Stomach rumble': 'rumble',
    'Fart': 'fart',
    'Throat clearing': 'ahem',
    'Snort': 'snort',
    'Pant': 'pant',
    'Wheeze': 'wheeze',
    
    # More Specific Animal Sounds
    'Chirp, tweet': 'chirp',
    'Squawk': 'squawk',
    'Caw': 'caw',
    'Moo': 'moo',
    'Oink': 'oink',
    'Bleat': 'bleat',
    'Buzz': 'buzz',
    'Hiss': 'hiss',
    'Rattle (instrument)': 'rattle',
    
    # Mechanical/Electronic Specifics
    'Clock': 'tick',
    'Tick-tock': 'tick',
    'Mechanical fan': 'whir',
    'Air conditioning': 'hum',
    'Steam': 'hiss',
    'Dental drill': 'drill',
    'Cash register': 'ding',
    'Typewriter': 'clack',
    'Keyboard (computer)': 'click',
    
    # More Impact Sounds
    'Chop': 'chop',
    'Splinter': 'crack',
    'Crack': 'crack',
    'Snap': 'snap',
    'Clap': 'clap',
    'Slap': 'slap',
    'Smash': 'smash',
    'Crash': 'crash',
    'Shatter': 'shatter',
    
    # Transportation Details
    'Idling': 'idle',
    'Engine starting': 'start',
    'Car door': 'slam',
    'Turn signal': 'click',
    'Windshield wipers': 'swish',
    'Air brake': 'hiss',
    'Train horn': 'horn',
    'Boat horn': 'horn',
    
    # Nature/Weather Specifics
    'Wind chime': 'chime',
    'Rustling leaves': 'rustle',
    'Crackling fire': 'crackle',
    'Ice cracking': 'crack',
    'Snow crunching': 'crunch',
    
    # Food/Kitchen Specifics
    'Chopping (food)': 'chop',
    'Frying': 'sizzle',
    'Boiling water': 'bubble',
    'Percolator': 'gurgle',
    'Can opener': 'grind',
    'Bottle cap': 'pop',
    'Cork': 'pop',
    'Fizz': 'fizz',
    
    # Additional Onomatopoeia-worthy Sounds
    'Whoosh': 'whoosh',
    'Swish': 'swish',
    'Swoosh': 'swoosh',
    'Zoom': 'zoom',
    'Zing': 'zing',
    'Ping': 'ping',
    'Plop': 'plop',
    'Bloop': 'bloop',
    'Chirp': 'chirp',
    'Beep': 'beep',
    'Honk': 'honk',
    'Toot': 'toot',
    'Whistle': 'whistle'
}